services:
  hotel-db:
    image: postgres:17
    container_name: hotel-postgres-container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5454:5432"
    volumes:
      - hotel_postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  hotel-backend:
    container_name: hotel-backend
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "5045:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MyHotel=${DB_CONNECTION_STRING}
    depends_on:
      - hotel-db
    volumes:
      - ./../data-keys:/root/.aspnet/DataProtection-Keys  # опция: сохранять keys между перезапусками

  hotel-frontend:
    container_name: hotel-frontend
    build:
      context: ../../hotel-frontend
      dockerfile: Dockerfile.dev
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:5045 # если фронт обращается к бэку
    command: [ "npm", "run", "dev", "--", "--host", "0.0.0.0" ]
    ports:
      - "5147:3000"   # dev server (CRA/Vite)
    depends_on:
      - hotel-backend

volumes:
  hotel_postgres_data: