services:
  hotel-db:
    image: postgres:17
    container_name: hotel-postgres-container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5454:5432"
    volumes:
      - hotel_postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  hotel-backend:
    container_name: hotel-backend
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "5045:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MyDbContext=${DB_CONNECTION_STRING}
    depends_on:
      - hotel-db
    volumes:
      - ../Static:/app/Static
      - ./../data-keys:/root/.aspnet/DataProtection-Keys  # опция: сохранять keys между перезапусками

  frontend:
    build:
      context: ../../hotel-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    depends_on:
      - hotel-backend
    restart: unless-stopped

volumes:
  hotel_postgres_data: